spring.application.name=news-retrieval
gemini.api-key=${GEMINI_API_KEY:}
gemini.model=gemini-3-flash-preview
openai.api-key=${OPENAI_API_KEY:}
openai.model=gpt-5-mini

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/news_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
app.pagination.default-limit=20